/*
 * WeShare API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Applications.Weshare.Swagger.Client;
using Applications.Weshare.Swagger.Model;

namespace Applications.Weshare.Swagger.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IExpensesApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create a new expense for a person
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newExpenseDTO"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ExpenseDTO</returns>
        ExpenseDTO CreateExpense(NewExpenseDTO? newExpenseDTO = default(NewExpenseDTO?), int operationIndex = 0);

        /// <summary>
        /// Create a new expense for a person
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newExpenseDTO"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ExpenseDTO</returns>
        ApiResponse<ExpenseDTO> CreateExpenseWithHttpInfo(NewExpenseDTO? newExpenseDTO = default(NewExpenseDTO?), int operationIndex = 0);
        /// <summary>
        /// Find all expenses
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;ExpenseDTO&gt;</returns>
        List<ExpenseDTO> FindAllExpenses(int operationIndex = 0);

        /// <summary>
        /// Find all expenses
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;ExpenseDTO&gt;</returns>
        ApiResponse<List<ExpenseDTO>> FindAllExpensesWithHttpInfo(int operationIndex = 0);
        /// <summary>
        /// Find an expense by ID
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="expenseId">The expense ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ExpenseDTO</returns>
        ExpenseDTO FindExpenseById(int expenseId, int operationIndex = 0);

        /// <summary>
        /// Find an expense by ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="expenseId">The expense ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ExpenseDTO</returns>
        ApiResponse<ExpenseDTO> FindExpenseByIdWithHttpInfo(int expenseId, int operationIndex = 0);
        /// <summary>
        /// Find expenses for a person
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personId">The ID of the person</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;ExpenseDTO&gt;</returns>
        List<ExpenseDTO> FindExpensesByPerson(int personId, int operationIndex = 0);

        /// <summary>
        /// Find expenses for a person
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personId">The ID of the person</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;ExpenseDTO&gt;</returns>
        ApiResponse<List<ExpenseDTO>> FindExpensesByPersonWithHttpInfo(int personId, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IExpensesApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Create a new expense for a person
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newExpenseDTO"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ExpenseDTO</returns>
        System.Threading.Tasks.Task<ExpenseDTO> CreateExpenseAsync(NewExpenseDTO? newExpenseDTO = default(NewExpenseDTO?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Create a new expense for a person
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newExpenseDTO"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ExpenseDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<ExpenseDTO>> CreateExpenseWithHttpInfoAsync(NewExpenseDTO? newExpenseDTO = default(NewExpenseDTO?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Find all expenses
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;ExpenseDTO&gt;</returns>
        System.Threading.Tasks.Task<List<ExpenseDTO>> FindAllExpensesAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Find all expenses
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;ExpenseDTO&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<ExpenseDTO>>> FindAllExpensesWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Find an expense by ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="expenseId">The expense ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ExpenseDTO</returns>
        System.Threading.Tasks.Task<ExpenseDTO> FindExpenseByIdAsync(int expenseId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Find an expense by ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="expenseId">The expense ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ExpenseDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<ExpenseDTO>> FindExpenseByIdWithHttpInfoAsync(int expenseId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Find expenses for a person
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personId">The ID of the person</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;ExpenseDTO&gt;</returns>
        System.Threading.Tasks.Task<List<ExpenseDTO>> FindExpensesByPersonAsync(int personId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Find expenses for a person
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personId">The ID of the person</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;ExpenseDTO&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<ExpenseDTO>>> FindExpensesByPersonWithHttpInfoAsync(int personId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IExpensesApi : IExpensesApiSync, IExpensesApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ExpensesApi : IExpensesApi
    {
        private Applications.Weshare.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ExpensesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ExpensesApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ExpensesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ExpensesApi(string basePath)
        {
            this.Configuration = Applications.Weshare.Swagger.Client.Configuration.MergeConfigurations(
                Applications.Weshare.Swagger.Client.GlobalConfiguration.Instance,
                new Applications.Weshare.Swagger.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Applications.Weshare.Swagger.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Applications.Weshare.Swagger.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Applications.Weshare.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ExpensesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ExpensesApi(Applications.Weshare.Swagger.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Applications.Weshare.Swagger.Client.Configuration.MergeConfigurations(
                Applications.Weshare.Swagger.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Applications.Weshare.Swagger.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Applications.Weshare.Swagger.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Applications.Weshare.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ExpensesApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public ExpensesApi(Applications.Weshare.Swagger.Client.ISynchronousClient client, Applications.Weshare.Swagger.Client.IAsynchronousClient asyncClient, Applications.Weshare.Swagger.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Applications.Weshare.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Applications.Weshare.Swagger.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Applications.Weshare.Swagger.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Applications.Weshare.Swagger.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Applications.Weshare.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Create a new expense for a person 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newExpenseDTO"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ExpenseDTO</returns>
        public ExpenseDTO CreateExpense(NewExpenseDTO? newExpenseDTO = default(NewExpenseDTO?), int operationIndex = 0)
        {
            Applications.Weshare.Swagger.Client.ApiResponse<ExpenseDTO> localVarResponse = CreateExpenseWithHttpInfo(newExpenseDTO);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a new expense for a person 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newExpenseDTO"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ExpenseDTO</returns>
        public Applications.Weshare.Swagger.Client.ApiResponse<ExpenseDTO> CreateExpenseWithHttpInfo(NewExpenseDTO? newExpenseDTO = default(NewExpenseDTO?), int operationIndex = 0)
        {
            Applications.Weshare.Swagger.Client.RequestOptions localVarRequestOptions = new Applications.Weshare.Swagger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = newExpenseDTO;

            localVarRequestOptions.Operation = "ExpensesApi.CreateExpense";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<ExpenseDTO>("/api/expenses", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateExpense", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create a new expense for a person 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newExpenseDTO"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ExpenseDTO</returns>
        public async System.Threading.Tasks.Task<ExpenseDTO> CreateExpenseAsync(NewExpenseDTO? newExpenseDTO = default(NewExpenseDTO?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Applications.Weshare.Swagger.Client.ApiResponse<ExpenseDTO> localVarResponse = await CreateExpenseWithHttpInfoAsync(newExpenseDTO, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a new expense for a person 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newExpenseDTO"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ExpenseDTO)</returns>
        public async System.Threading.Tasks.Task<Applications.Weshare.Swagger.Client.ApiResponse<ExpenseDTO>> CreateExpenseWithHttpInfoAsync(NewExpenseDTO? newExpenseDTO = default(NewExpenseDTO?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Applications.Weshare.Swagger.Client.RequestOptions localVarRequestOptions = new Applications.Weshare.Swagger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = newExpenseDTO;

            localVarRequestOptions.Operation = "ExpensesApi.CreateExpense";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<ExpenseDTO>("/api/expenses", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateExpense", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Find all expenses 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;ExpenseDTO&gt;</returns>
        public List<ExpenseDTO> FindAllExpenses(int operationIndex = 0)
        {
            Applications.Weshare.Swagger.Client.ApiResponse<List<ExpenseDTO>> localVarResponse = FindAllExpensesWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Find all expenses 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;ExpenseDTO&gt;</returns>
        public Applications.Weshare.Swagger.Client.ApiResponse<List<ExpenseDTO>> FindAllExpensesWithHttpInfo(int operationIndex = 0)
        {
            Applications.Weshare.Swagger.Client.RequestOptions localVarRequestOptions = new Applications.Weshare.Swagger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "ExpensesApi.FindAllExpenses";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<List<ExpenseDTO>>("/api/expenses", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("FindAllExpenses", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Find all expenses 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;ExpenseDTO&gt;</returns>
        public async System.Threading.Tasks.Task<List<ExpenseDTO>> FindAllExpensesAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Applications.Weshare.Swagger.Client.ApiResponse<List<ExpenseDTO>> localVarResponse = await FindAllExpensesWithHttpInfoAsync(operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Find all expenses 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;ExpenseDTO&gt;)</returns>
        public async System.Threading.Tasks.Task<Applications.Weshare.Swagger.Client.ApiResponse<List<ExpenseDTO>>> FindAllExpensesWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Applications.Weshare.Swagger.Client.RequestOptions localVarRequestOptions = new Applications.Weshare.Swagger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "ExpensesApi.FindAllExpenses";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<List<ExpenseDTO>>("/api/expenses", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("FindAllExpenses", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Find an expense by ID 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="expenseId">The expense ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ExpenseDTO</returns>
        public ExpenseDTO FindExpenseById(int expenseId, int operationIndex = 0)
        {
            Applications.Weshare.Swagger.Client.ApiResponse<ExpenseDTO> localVarResponse = FindExpenseByIdWithHttpInfo(expenseId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Find an expense by ID 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="expenseId">The expense ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ExpenseDTO</returns>
        public Applications.Weshare.Swagger.Client.ApiResponse<ExpenseDTO> FindExpenseByIdWithHttpInfo(int expenseId, int operationIndex = 0)
        {
            Applications.Weshare.Swagger.Client.RequestOptions localVarRequestOptions = new Applications.Weshare.Swagger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("expenseId", Applications.Weshare.Swagger.Client.ClientUtils.ParameterToString(expenseId)); // path parameter

            localVarRequestOptions.Operation = "ExpensesApi.FindExpenseById";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<ExpenseDTO>("/api/expenses/{expenseId}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("FindExpenseById", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Find an expense by ID 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="expenseId">The expense ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ExpenseDTO</returns>
        public async System.Threading.Tasks.Task<ExpenseDTO> FindExpenseByIdAsync(int expenseId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Applications.Weshare.Swagger.Client.ApiResponse<ExpenseDTO> localVarResponse = await FindExpenseByIdWithHttpInfoAsync(expenseId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Find an expense by ID 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="expenseId">The expense ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ExpenseDTO)</returns>
        public async System.Threading.Tasks.Task<Applications.Weshare.Swagger.Client.ApiResponse<ExpenseDTO>> FindExpenseByIdWithHttpInfoAsync(int expenseId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Applications.Weshare.Swagger.Client.RequestOptions localVarRequestOptions = new Applications.Weshare.Swagger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("expenseId", Applications.Weshare.Swagger.Client.ClientUtils.ParameterToString(expenseId)); // path parameter

            localVarRequestOptions.Operation = "ExpensesApi.FindExpenseById";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<ExpenseDTO>("/api/expenses/{expenseId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("FindExpenseById", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Find expenses for a person 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personId">The ID of the person</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;ExpenseDTO&gt;</returns>
        public List<ExpenseDTO> FindExpensesByPerson(int personId, int operationIndex = 0)
        {
            Applications.Weshare.Swagger.Client.ApiResponse<List<ExpenseDTO>> localVarResponse = FindExpensesByPersonWithHttpInfo(personId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Find expenses for a person 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personId">The ID of the person</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;ExpenseDTO&gt;</returns>
        public Applications.Weshare.Swagger.Client.ApiResponse<List<ExpenseDTO>> FindExpensesByPersonWithHttpInfo(int personId, int operationIndex = 0)
        {
            Applications.Weshare.Swagger.Client.RequestOptions localVarRequestOptions = new Applications.Weshare.Swagger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("personId", Applications.Weshare.Swagger.Client.ClientUtils.ParameterToString(personId)); // path parameter

            localVarRequestOptions.Operation = "ExpensesApi.FindExpensesByPerson";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<List<ExpenseDTO>>("/api/expenses/person/{personId}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("FindExpensesByPerson", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Find expenses for a person 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personId">The ID of the person</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;ExpenseDTO&gt;</returns>
        public async System.Threading.Tasks.Task<List<ExpenseDTO>> FindExpensesByPersonAsync(int personId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Applications.Weshare.Swagger.Client.ApiResponse<List<ExpenseDTO>> localVarResponse = await FindExpensesByPersonWithHttpInfoAsync(personId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Find expenses for a person 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personId">The ID of the person</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;ExpenseDTO&gt;)</returns>
        public async System.Threading.Tasks.Task<Applications.Weshare.Swagger.Client.ApiResponse<List<ExpenseDTO>>> FindExpensesByPersonWithHttpInfoAsync(int personId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Applications.Weshare.Swagger.Client.RequestOptions localVarRequestOptions = new Applications.Weshare.Swagger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("personId", Applications.Weshare.Swagger.Client.ClientUtils.ParameterToString(personId)); // path parameter

            localVarRequestOptions.Operation = "ExpensesApi.FindExpensesByPerson";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<List<ExpenseDTO>>("/api/expenses/person/{personId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("FindExpensesByPerson", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
