/*
 * WeShare API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Applications.Weshare.Swagger.Client;
using Applications.Weshare.Swagger.Model;

namespace Applications.Weshare.Swagger.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPaymentsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Find all payments made by a person
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personId">The ID of the person</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;PaymentDTO&gt;</returns>
        List<PaymentDTO> FindPaymentsMadeByPerson(int personId, int operationIndex = 0);

        /// <summary>
        /// Find all payments made by a person
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personId">The ID of the person</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;PaymentDTO&gt;</returns>
        ApiResponse<List<PaymentDTO>> FindPaymentsMadeByPersonWithHttpInfo(int personId, int operationIndex = 0);
        /// <summary>
        /// Pay a payment request
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newPaymentDTO"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PaymentDTO</returns>
        PaymentDTO PayPaymentRequest(NewPaymentDTO? newPaymentDTO = default(NewPaymentDTO?), int operationIndex = 0);

        /// <summary>
        /// Pay a payment request
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newPaymentDTO"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PaymentDTO</returns>
        ApiResponse<PaymentDTO> PayPaymentRequestWithHttpInfo(NewPaymentDTO? newPaymentDTO = default(NewPaymentDTO?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPaymentsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Find all payments made by a person
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personId">The ID of the person</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;PaymentDTO&gt;</returns>
        System.Threading.Tasks.Task<List<PaymentDTO>> FindPaymentsMadeByPersonAsync(int personId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Find all payments made by a person
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personId">The ID of the person</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;PaymentDTO&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<PaymentDTO>>> FindPaymentsMadeByPersonWithHttpInfoAsync(int personId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Pay a payment request
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newPaymentDTO"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PaymentDTO</returns>
        System.Threading.Tasks.Task<PaymentDTO> PayPaymentRequestAsync(NewPaymentDTO? newPaymentDTO = default(NewPaymentDTO?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Pay a payment request
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newPaymentDTO"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PaymentDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<PaymentDTO>> PayPaymentRequestWithHttpInfoAsync(NewPaymentDTO? newPaymentDTO = default(NewPaymentDTO?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPaymentsApi : IPaymentsApiSync, IPaymentsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class PaymentsApi : IPaymentsApi
    {
        private Applications.Weshare.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public PaymentsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public PaymentsApi(string basePath)
        {
            this.Configuration = Applications.Weshare.Swagger.Client.Configuration.MergeConfigurations(
                Applications.Weshare.Swagger.Client.GlobalConfiguration.Instance,
                new Applications.Weshare.Swagger.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Applications.Weshare.Swagger.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Applications.Weshare.Swagger.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Applications.Weshare.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public PaymentsApi(Applications.Weshare.Swagger.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Applications.Weshare.Swagger.Client.Configuration.MergeConfigurations(
                Applications.Weshare.Swagger.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Applications.Weshare.Swagger.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Applications.Weshare.Swagger.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Applications.Weshare.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public PaymentsApi(Applications.Weshare.Swagger.Client.ISynchronousClient client, Applications.Weshare.Swagger.Client.IAsynchronousClient asyncClient, Applications.Weshare.Swagger.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Applications.Weshare.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Applications.Weshare.Swagger.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Applications.Weshare.Swagger.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Applications.Weshare.Swagger.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Applications.Weshare.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Find all payments made by a person 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personId">The ID of the person</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;PaymentDTO&gt;</returns>
        public List<PaymentDTO> FindPaymentsMadeByPerson(int personId, int operationIndex = 0)
        {
            Applications.Weshare.Swagger.Client.ApiResponse<List<PaymentDTO>> localVarResponse = FindPaymentsMadeByPersonWithHttpInfo(personId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Find all payments made by a person 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personId">The ID of the person</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;PaymentDTO&gt;</returns>
        public Applications.Weshare.Swagger.Client.ApiResponse<List<PaymentDTO>> FindPaymentsMadeByPersonWithHttpInfo(int personId, int operationIndex = 0)
        {
            Applications.Weshare.Swagger.Client.RequestOptions localVarRequestOptions = new Applications.Weshare.Swagger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("personId", Applications.Weshare.Swagger.Client.ClientUtils.ParameterToString(personId)); // path parameter

            localVarRequestOptions.Operation = "PaymentsApi.FindPaymentsMadeByPerson";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<List<PaymentDTO>>("/api/payments/madeby/{personId}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("FindPaymentsMadeByPerson", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Find all payments made by a person 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personId">The ID of the person</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;PaymentDTO&gt;</returns>
        public async System.Threading.Tasks.Task<List<PaymentDTO>> FindPaymentsMadeByPersonAsync(int personId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Applications.Weshare.Swagger.Client.ApiResponse<List<PaymentDTO>> localVarResponse = await FindPaymentsMadeByPersonWithHttpInfoAsync(personId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Find all payments made by a person 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personId">The ID of the person</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;PaymentDTO&gt;)</returns>
        public async System.Threading.Tasks.Task<Applications.Weshare.Swagger.Client.ApiResponse<List<PaymentDTO>>> FindPaymentsMadeByPersonWithHttpInfoAsync(int personId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Applications.Weshare.Swagger.Client.RequestOptions localVarRequestOptions = new Applications.Weshare.Swagger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("personId", Applications.Weshare.Swagger.Client.ClientUtils.ParameterToString(personId)); // path parameter

            localVarRequestOptions.Operation = "PaymentsApi.FindPaymentsMadeByPerson";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<List<PaymentDTO>>("/api/payments/madeby/{personId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("FindPaymentsMadeByPerson", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Pay a payment request 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newPaymentDTO"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PaymentDTO</returns>
        public PaymentDTO PayPaymentRequest(NewPaymentDTO? newPaymentDTO = default(NewPaymentDTO?), int operationIndex = 0)
        {
            Applications.Weshare.Swagger.Client.ApiResponse<PaymentDTO> localVarResponse = PayPaymentRequestWithHttpInfo(newPaymentDTO);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Pay a payment request 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newPaymentDTO"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PaymentDTO</returns>
        public Applications.Weshare.Swagger.Client.ApiResponse<PaymentDTO> PayPaymentRequestWithHttpInfo(NewPaymentDTO? newPaymentDTO = default(NewPaymentDTO?), int operationIndex = 0)
        {
            Applications.Weshare.Swagger.Client.RequestOptions localVarRequestOptions = new Applications.Weshare.Swagger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = newPaymentDTO;

            localVarRequestOptions.Operation = "PaymentsApi.PayPaymentRequest";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<PaymentDTO>("/api/payments", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PayPaymentRequest", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Pay a payment request 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newPaymentDTO"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PaymentDTO</returns>
        public async System.Threading.Tasks.Task<PaymentDTO> PayPaymentRequestAsync(NewPaymentDTO? newPaymentDTO = default(NewPaymentDTO?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Applications.Weshare.Swagger.Client.ApiResponse<PaymentDTO> localVarResponse = await PayPaymentRequestWithHttpInfoAsync(newPaymentDTO, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Pay a payment request 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newPaymentDTO"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PaymentDTO)</returns>
        public async System.Threading.Tasks.Task<Applications.Weshare.Swagger.Client.ApiResponse<PaymentDTO>> PayPaymentRequestWithHttpInfoAsync(NewPaymentDTO? newPaymentDTO = default(NewPaymentDTO?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Applications.Weshare.Swagger.Client.RequestOptions localVarRequestOptions = new Applications.Weshare.Swagger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = newPaymentDTO;

            localVarRequestOptions.Operation = "PaymentsApi.PayPaymentRequest";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<PaymentDTO>("/api/payments", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PayPaymentRequest", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
