/*
 * WeShare API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Applications.Weshare.Swagger.Client;
using Applications.Weshare.Swagger.Model;

namespace Applications.Weshare.Swagger.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPaymentRequestsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create a new payment request
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newPaymentRequestDTO"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PaymentRequestDTO</returns>
        PaymentRequestDTO CreatePaymentRequest(NewPaymentRequestDTO? newPaymentRequestDTO = default(NewPaymentRequestDTO?), int operationIndex = 0);

        /// <summary>
        /// Create a new payment request
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newPaymentRequestDTO"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PaymentRequestDTO</returns>
        ApiResponse<PaymentRequestDTO> CreatePaymentRequestWithHttpInfo(NewPaymentRequestDTO? newPaymentRequestDTO = default(NewPaymentRequestDTO?), int operationIndex = 0);
        /// <summary>
        /// Find all payment requests
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;PaymentRequestDTO&gt;</returns>
        List<PaymentRequestDTO> FindAllPaymentRequests(int operationIndex = 0);

        /// <summary>
        /// Find all payment requests
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;PaymentRequestDTO&gt;</returns>
        ApiResponse<List<PaymentRequestDTO>> FindAllPaymentRequestsWithHttpInfo(int operationIndex = 0);
        /// <summary>
        /// Find payment requests received by a person
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personId">The ID of the person that received payment requests</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;PaymentRequestDTO&gt;</returns>
        List<PaymentRequestDTO> FindPaymentRequestsReceived(int personId, int operationIndex = 0);

        /// <summary>
        /// Find payment requests received by a person
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personId">The ID of the person that received payment requests</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;PaymentRequestDTO&gt;</returns>
        ApiResponse<List<PaymentRequestDTO>> FindPaymentRequestsReceivedWithHttpInfo(int personId, int operationIndex = 0);
        /// <summary>
        /// Find payment requests sent by a person
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personId">The ID of the person that sent payment requests</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;PaymentRequestDTO&gt;</returns>
        List<PaymentRequestDTO> FindPaymentRequestsSent(int personId, int operationIndex = 0);

        /// <summary>
        /// Find payment requests sent by a person
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personId">The ID of the person that sent payment requests</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;PaymentRequestDTO&gt;</returns>
        ApiResponse<List<PaymentRequestDTO>> FindPaymentRequestsSentWithHttpInfo(int personId, int operationIndex = 0);
        /// <summary>
        /// Get payment request by ID
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="paymentRequestId">The payment request ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PaymentRequestDTO</returns>
        PaymentRequestDTO GetPaymentRequestById(int paymentRequestId, int operationIndex = 0);

        /// <summary>
        /// Get payment request by ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="paymentRequestId">The payment request ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PaymentRequestDTO</returns>
        ApiResponse<PaymentRequestDTO> GetPaymentRequestByIdWithHttpInfo(int paymentRequestId, int operationIndex = 0);
        /// <summary>
        /// Recall an unpaid payment request
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="paymentRequestId">The payment request ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void RecallUnpaidPaymentRequest(int paymentRequestId, int operationIndex = 0);

        /// <summary>
        /// Recall an unpaid payment request
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="paymentRequestId">The payment request ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> RecallUnpaidPaymentRequestWithHttpInfo(int paymentRequestId, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPaymentRequestsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Create a new payment request
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newPaymentRequestDTO"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PaymentRequestDTO</returns>
        System.Threading.Tasks.Task<PaymentRequestDTO> CreatePaymentRequestAsync(NewPaymentRequestDTO? newPaymentRequestDTO = default(NewPaymentRequestDTO?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Create a new payment request
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newPaymentRequestDTO"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PaymentRequestDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<PaymentRequestDTO>> CreatePaymentRequestWithHttpInfoAsync(NewPaymentRequestDTO? newPaymentRequestDTO = default(NewPaymentRequestDTO?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Find all payment requests
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;PaymentRequestDTO&gt;</returns>
        System.Threading.Tasks.Task<List<PaymentRequestDTO>> FindAllPaymentRequestsAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Find all payment requests
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;PaymentRequestDTO&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<PaymentRequestDTO>>> FindAllPaymentRequestsWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Find payment requests received by a person
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personId">The ID of the person that received payment requests</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;PaymentRequestDTO&gt;</returns>
        System.Threading.Tasks.Task<List<PaymentRequestDTO>> FindPaymentRequestsReceivedAsync(int personId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Find payment requests received by a person
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personId">The ID of the person that received payment requests</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;PaymentRequestDTO&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<PaymentRequestDTO>>> FindPaymentRequestsReceivedWithHttpInfoAsync(int personId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Find payment requests sent by a person
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personId">The ID of the person that sent payment requests</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;PaymentRequestDTO&gt;</returns>
        System.Threading.Tasks.Task<List<PaymentRequestDTO>> FindPaymentRequestsSentAsync(int personId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Find payment requests sent by a person
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personId">The ID of the person that sent payment requests</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;PaymentRequestDTO&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<PaymentRequestDTO>>> FindPaymentRequestsSentWithHttpInfoAsync(int personId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get payment request by ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="paymentRequestId">The payment request ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PaymentRequestDTO</returns>
        System.Threading.Tasks.Task<PaymentRequestDTO> GetPaymentRequestByIdAsync(int paymentRequestId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get payment request by ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="paymentRequestId">The payment request ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PaymentRequestDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<PaymentRequestDTO>> GetPaymentRequestByIdWithHttpInfoAsync(int paymentRequestId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Recall an unpaid payment request
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="paymentRequestId">The payment request ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task RecallUnpaidPaymentRequestAsync(int paymentRequestId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Recall an unpaid payment request
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="paymentRequestId">The payment request ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> RecallUnpaidPaymentRequestWithHttpInfoAsync(int paymentRequestId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPaymentRequestsApi : IPaymentRequestsApiSync, IPaymentRequestsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class PaymentRequestsApi : IPaymentRequestsApi
    {
        private Applications.Weshare.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentRequestsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public PaymentRequestsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentRequestsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public PaymentRequestsApi(string basePath)
        {
            this.Configuration = Applications.Weshare.Swagger.Client.Configuration.MergeConfigurations(
                Applications.Weshare.Swagger.Client.GlobalConfiguration.Instance,
                new Applications.Weshare.Swagger.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Applications.Weshare.Swagger.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Applications.Weshare.Swagger.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Applications.Weshare.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentRequestsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public PaymentRequestsApi(Applications.Weshare.Swagger.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Applications.Weshare.Swagger.Client.Configuration.MergeConfigurations(
                Applications.Weshare.Swagger.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Applications.Weshare.Swagger.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Applications.Weshare.Swagger.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Applications.Weshare.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentRequestsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public PaymentRequestsApi(Applications.Weshare.Swagger.Client.ISynchronousClient client, Applications.Weshare.Swagger.Client.IAsynchronousClient asyncClient, Applications.Weshare.Swagger.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Applications.Weshare.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Applications.Weshare.Swagger.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Applications.Weshare.Swagger.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Applications.Weshare.Swagger.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Applications.Weshare.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Create a new payment request 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newPaymentRequestDTO"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PaymentRequestDTO</returns>
        public PaymentRequestDTO CreatePaymentRequest(NewPaymentRequestDTO? newPaymentRequestDTO = default(NewPaymentRequestDTO?), int operationIndex = 0)
        {
            Applications.Weshare.Swagger.Client.ApiResponse<PaymentRequestDTO> localVarResponse = CreatePaymentRequestWithHttpInfo(newPaymentRequestDTO);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a new payment request 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newPaymentRequestDTO"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PaymentRequestDTO</returns>
        public Applications.Weshare.Swagger.Client.ApiResponse<PaymentRequestDTO> CreatePaymentRequestWithHttpInfo(NewPaymentRequestDTO? newPaymentRequestDTO = default(NewPaymentRequestDTO?), int operationIndex = 0)
        {
            Applications.Weshare.Swagger.Client.RequestOptions localVarRequestOptions = new Applications.Weshare.Swagger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = newPaymentRequestDTO;

            localVarRequestOptions.Operation = "PaymentRequestsApi.CreatePaymentRequest";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<PaymentRequestDTO>("/api/paymentrequests", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreatePaymentRequest", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create a new payment request 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newPaymentRequestDTO"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PaymentRequestDTO</returns>
        public async System.Threading.Tasks.Task<PaymentRequestDTO> CreatePaymentRequestAsync(NewPaymentRequestDTO? newPaymentRequestDTO = default(NewPaymentRequestDTO?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Applications.Weshare.Swagger.Client.ApiResponse<PaymentRequestDTO> localVarResponse = await CreatePaymentRequestWithHttpInfoAsync(newPaymentRequestDTO, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a new payment request 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newPaymentRequestDTO"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PaymentRequestDTO)</returns>
        public async System.Threading.Tasks.Task<Applications.Weshare.Swagger.Client.ApiResponse<PaymentRequestDTO>> CreatePaymentRequestWithHttpInfoAsync(NewPaymentRequestDTO? newPaymentRequestDTO = default(NewPaymentRequestDTO?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Applications.Weshare.Swagger.Client.RequestOptions localVarRequestOptions = new Applications.Weshare.Swagger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = newPaymentRequestDTO;

            localVarRequestOptions.Operation = "PaymentRequestsApi.CreatePaymentRequest";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<PaymentRequestDTO>("/api/paymentrequests", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreatePaymentRequest", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Find all payment requests 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;PaymentRequestDTO&gt;</returns>
        public List<PaymentRequestDTO> FindAllPaymentRequests(int operationIndex = 0)
        {
            Applications.Weshare.Swagger.Client.ApiResponse<List<PaymentRequestDTO>> localVarResponse = FindAllPaymentRequestsWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Find all payment requests 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;PaymentRequestDTO&gt;</returns>
        public Applications.Weshare.Swagger.Client.ApiResponse<List<PaymentRequestDTO>> FindAllPaymentRequestsWithHttpInfo(int operationIndex = 0)
        {
            Applications.Weshare.Swagger.Client.RequestOptions localVarRequestOptions = new Applications.Weshare.Swagger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "PaymentRequestsApi.FindAllPaymentRequests";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<List<PaymentRequestDTO>>("/api/paymentrequests", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("FindAllPaymentRequests", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Find all payment requests 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;PaymentRequestDTO&gt;</returns>
        public async System.Threading.Tasks.Task<List<PaymentRequestDTO>> FindAllPaymentRequestsAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Applications.Weshare.Swagger.Client.ApiResponse<List<PaymentRequestDTO>> localVarResponse = await FindAllPaymentRequestsWithHttpInfoAsync(operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Find all payment requests 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;PaymentRequestDTO&gt;)</returns>
        public async System.Threading.Tasks.Task<Applications.Weshare.Swagger.Client.ApiResponse<List<PaymentRequestDTO>>> FindAllPaymentRequestsWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Applications.Weshare.Swagger.Client.RequestOptions localVarRequestOptions = new Applications.Weshare.Swagger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "PaymentRequestsApi.FindAllPaymentRequests";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<List<PaymentRequestDTO>>("/api/paymentrequests", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("FindAllPaymentRequests", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Find payment requests received by a person 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personId">The ID of the person that received payment requests</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;PaymentRequestDTO&gt;</returns>
        public List<PaymentRequestDTO> FindPaymentRequestsReceived(int personId, int operationIndex = 0)
        {
            Applications.Weshare.Swagger.Client.ApiResponse<List<PaymentRequestDTO>> localVarResponse = FindPaymentRequestsReceivedWithHttpInfo(personId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Find payment requests received by a person 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personId">The ID of the person that received payment requests</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;PaymentRequestDTO&gt;</returns>
        public Applications.Weshare.Swagger.Client.ApiResponse<List<PaymentRequestDTO>> FindPaymentRequestsReceivedWithHttpInfo(int personId, int operationIndex = 0)
        {
            Applications.Weshare.Swagger.Client.RequestOptions localVarRequestOptions = new Applications.Weshare.Swagger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("personId", Applications.Weshare.Swagger.Client.ClientUtils.ParameterToString(personId)); // path parameter

            localVarRequestOptions.Operation = "PaymentRequestsApi.FindPaymentRequestsReceived";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<List<PaymentRequestDTO>>("/api/paymentrequests/received/{personId}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("FindPaymentRequestsReceived", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Find payment requests received by a person 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personId">The ID of the person that received payment requests</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;PaymentRequestDTO&gt;</returns>
        public async System.Threading.Tasks.Task<List<PaymentRequestDTO>> FindPaymentRequestsReceivedAsync(int personId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Applications.Weshare.Swagger.Client.ApiResponse<List<PaymentRequestDTO>> localVarResponse = await FindPaymentRequestsReceivedWithHttpInfoAsync(personId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Find payment requests received by a person 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personId">The ID of the person that received payment requests</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;PaymentRequestDTO&gt;)</returns>
        public async System.Threading.Tasks.Task<Applications.Weshare.Swagger.Client.ApiResponse<List<PaymentRequestDTO>>> FindPaymentRequestsReceivedWithHttpInfoAsync(int personId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Applications.Weshare.Swagger.Client.RequestOptions localVarRequestOptions = new Applications.Weshare.Swagger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("personId", Applications.Weshare.Swagger.Client.ClientUtils.ParameterToString(personId)); // path parameter

            localVarRequestOptions.Operation = "PaymentRequestsApi.FindPaymentRequestsReceived";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<List<PaymentRequestDTO>>("/api/paymentrequests/received/{personId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("FindPaymentRequestsReceived", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Find payment requests sent by a person 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personId">The ID of the person that sent payment requests</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;PaymentRequestDTO&gt;</returns>
        public List<PaymentRequestDTO> FindPaymentRequestsSent(int personId, int operationIndex = 0)
        {
            Applications.Weshare.Swagger.Client.ApiResponse<List<PaymentRequestDTO>> localVarResponse = FindPaymentRequestsSentWithHttpInfo(personId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Find payment requests sent by a person 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personId">The ID of the person that sent payment requests</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;PaymentRequestDTO&gt;</returns>
        public Applications.Weshare.Swagger.Client.ApiResponse<List<PaymentRequestDTO>> FindPaymentRequestsSentWithHttpInfo(int personId, int operationIndex = 0)
        {
            Applications.Weshare.Swagger.Client.RequestOptions localVarRequestOptions = new Applications.Weshare.Swagger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("personId", Applications.Weshare.Swagger.Client.ClientUtils.ParameterToString(personId)); // path parameter

            localVarRequestOptions.Operation = "PaymentRequestsApi.FindPaymentRequestsSent";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<List<PaymentRequestDTO>>("/api/paymentrequests/sent/{personId}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("FindPaymentRequestsSent", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Find payment requests sent by a person 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personId">The ID of the person that sent payment requests</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;PaymentRequestDTO&gt;</returns>
        public async System.Threading.Tasks.Task<List<PaymentRequestDTO>> FindPaymentRequestsSentAsync(int personId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Applications.Weshare.Swagger.Client.ApiResponse<List<PaymentRequestDTO>> localVarResponse = await FindPaymentRequestsSentWithHttpInfoAsync(personId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Find payment requests sent by a person 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="personId">The ID of the person that sent payment requests</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;PaymentRequestDTO&gt;)</returns>
        public async System.Threading.Tasks.Task<Applications.Weshare.Swagger.Client.ApiResponse<List<PaymentRequestDTO>>> FindPaymentRequestsSentWithHttpInfoAsync(int personId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Applications.Weshare.Swagger.Client.RequestOptions localVarRequestOptions = new Applications.Weshare.Swagger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("personId", Applications.Weshare.Swagger.Client.ClientUtils.ParameterToString(personId)); // path parameter

            localVarRequestOptions.Operation = "PaymentRequestsApi.FindPaymentRequestsSent";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<List<PaymentRequestDTO>>("/api/paymentrequests/sent/{personId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("FindPaymentRequestsSent", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get payment request by ID 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="paymentRequestId">The payment request ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PaymentRequestDTO</returns>
        public PaymentRequestDTO GetPaymentRequestById(int paymentRequestId, int operationIndex = 0)
        {
            Applications.Weshare.Swagger.Client.ApiResponse<PaymentRequestDTO> localVarResponse = GetPaymentRequestByIdWithHttpInfo(paymentRequestId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get payment request by ID 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="paymentRequestId">The payment request ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PaymentRequestDTO</returns>
        public Applications.Weshare.Swagger.Client.ApiResponse<PaymentRequestDTO> GetPaymentRequestByIdWithHttpInfo(int paymentRequestId, int operationIndex = 0)
        {
            Applications.Weshare.Swagger.Client.RequestOptions localVarRequestOptions = new Applications.Weshare.Swagger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("paymentRequestId", Applications.Weshare.Swagger.Client.ClientUtils.ParameterToString(paymentRequestId)); // path parameter

            localVarRequestOptions.Operation = "PaymentRequestsApi.GetPaymentRequestById";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<PaymentRequestDTO>("/api/paymentrequests/{paymentRequestId}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetPaymentRequestById", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get payment request by ID 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="paymentRequestId">The payment request ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PaymentRequestDTO</returns>
        public async System.Threading.Tasks.Task<PaymentRequestDTO> GetPaymentRequestByIdAsync(int paymentRequestId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Applications.Weshare.Swagger.Client.ApiResponse<PaymentRequestDTO> localVarResponse = await GetPaymentRequestByIdWithHttpInfoAsync(paymentRequestId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get payment request by ID 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="paymentRequestId">The payment request ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PaymentRequestDTO)</returns>
        public async System.Threading.Tasks.Task<Applications.Weshare.Swagger.Client.ApiResponse<PaymentRequestDTO>> GetPaymentRequestByIdWithHttpInfoAsync(int paymentRequestId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Applications.Weshare.Swagger.Client.RequestOptions localVarRequestOptions = new Applications.Weshare.Swagger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("paymentRequestId", Applications.Weshare.Swagger.Client.ClientUtils.ParameterToString(paymentRequestId)); // path parameter

            localVarRequestOptions.Operation = "PaymentRequestsApi.GetPaymentRequestById";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<PaymentRequestDTO>("/api/paymentrequests/{paymentRequestId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetPaymentRequestById", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Recall an unpaid payment request 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="paymentRequestId">The payment request ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void RecallUnpaidPaymentRequest(int paymentRequestId, int operationIndex = 0)
        {
            RecallUnpaidPaymentRequestWithHttpInfo(paymentRequestId);
        }

        /// <summary>
        /// Recall an unpaid payment request 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="paymentRequestId">The payment request ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Applications.Weshare.Swagger.Client.ApiResponse<Object> RecallUnpaidPaymentRequestWithHttpInfo(int paymentRequestId, int operationIndex = 0)
        {
            Applications.Weshare.Swagger.Client.RequestOptions localVarRequestOptions = new Applications.Weshare.Swagger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("paymentRequestId", Applications.Weshare.Swagger.Client.ClientUtils.ParameterToString(paymentRequestId)); // path parameter

            localVarRequestOptions.Operation = "PaymentRequestsApi.RecallUnpaidPaymentRequest";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Delete<Object>("/api/paymentrequests/{paymentRequestId}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RecallUnpaidPaymentRequest", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Recall an unpaid payment request 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="paymentRequestId">The payment request ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task RecallUnpaidPaymentRequestAsync(int paymentRequestId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await RecallUnpaidPaymentRequestWithHttpInfoAsync(paymentRequestId, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Recall an unpaid payment request 
        /// </summary>
        /// <exception cref="Applications.Weshare.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="paymentRequestId">The payment request ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Applications.Weshare.Swagger.Client.ApiResponse<Object>> RecallUnpaidPaymentRequestWithHttpInfoAsync(int paymentRequestId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Applications.Weshare.Swagger.Client.RequestOptions localVarRequestOptions = new Applications.Weshare.Swagger.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Applications.Weshare.Swagger.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("paymentRequestId", Applications.Weshare.Swagger.Client.ClientUtils.ParameterToString(paymentRequestId)); // path parameter

            localVarRequestOptions.Operation = "PaymentRequestsApi.RecallUnpaidPaymentRequest";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Object>("/api/paymentrequests/{paymentRequestId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RecallUnpaidPaymentRequest", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
